# -*- coding: utf-8 -*-
"""Speech-to-Text Transcription.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXKxd6dSP7-seTsbilIunW3ZxLadn1gp
"""

!pip install SpeechRecognition pydub

import speech_recognition as sr
from google.colab import files
from pydub import AudioSegment

print("Upload your MP3 file:")
uploaded=files.upload()

filename=list(uploaded.keys())[0]

audio=AudioSegment.from_file(filename,format="mp3")

audio.export("temp.wav",format="wav")

recognizer=sr.Recognizer()

with sr.AudioFile("temp.wav") as source:
    print("Extracting audio data")
    audio_data=recognizer.record(source)

try:
    text=recognizer.recognize_google(audio_data)
    print("\nResult\n")
    print(text)
except sr.UnknownValueError:
    print("Could not understand the audio, try more clear version")